# DB
db-host=localhost
db-name=pw
db-user=user
db-password=password

# Paths
patch-path=files
patch-new-dir=new
patch-cpw-dir=CPW

# Versions
min-launcher-ver=1
min-patcher-ver=1
min-element-ver=1

# Flags
remove-folders=true
remove-files=true
add-size=true