# DB
db-host=localhost
db-name=pw
db-user=user
db-password=password

# Paths
patch-path=files
patch-new-dir=new
patch-cpw-dir=CPW

# RSA
rsa-private-key=PRIVATE_KEY
rsa-public-key=PUBLIC_KEY
rsa-modus=1
rsa-private-x=1
rsa-public-x=65537

# Versions
min-launcher-ver=1
min-patcher-ver=1
min-element-ver=1

# Flags
remove-folders=true
remove-files=true
add-size=true